services:
  pytorch-env:
    command: bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    shm_size: '16gb'
    user: "${UID}:${GID}"
    image: ${USER}/pytorch:1131
    container_name: mydl
    build:
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${USER_NAME}
        - UID=${UID}
        - GID=${GID}
        - PASSWORD=${USER_NAME}
        - WORKDIR=${WORKDIR_CONTAINER}
      context: .
      shm_size: '16gb'
      dockerfile: Dockerfile
    tty: true
    volumes:
      - "${WORKDIR_LOCAL}:${WORKDIR_CONTAINER}"
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
